// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __lamW_h__
#define __lamW_h__

#include "lamW_RcppExports.h"

#endif // __lamW_h__
