// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/lamW.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// lambertW0_C
NumericVector lambertW0_C(NumericVector x);
static SEXP lamW_lambertW0_C_try(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(lambertW0_C(x));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP lamW_lambertW0_C(SEXP xSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(lamW_lambertW0_C_try(xSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// lambertWm1_C
NumericVector lambertWm1_C(NumericVector x);
static SEXP lamW_lambertWm1_C_try(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(lambertWm1_C(x));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP lamW_lambertWm1_C(SEXP xSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(lamW_lambertWm1_C_try(xSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}

// validate (ensure exported C++ functions exist before calling them)
static int lamW_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("NumericVector(*lambertW0_C)(NumericVector)");
        signatures.insert("NumericVector(*lambertWm1_C)(NumericVector)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP lamW_RcppExport_registerCCallable() { 
    R_RegisterCCallable("lamW", "lamW_lambertW0_C", (DL_FUNC)lamW_lambertW0_C_try);
    R_RegisterCCallable("lamW", "lamW_lambertWm1_C", (DL_FUNC)lamW_lambertWm1_C_try);
    R_RegisterCCallable("lamW", "lamW_RcppExport_validate", (DL_FUNC)lamW_RcppExport_validate);
    return R_NilValue;
}
