// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// lambertW0_C
NumericVector lambertW0_C(NumericVector x);
RcppExport SEXP lamW_lambertW0_C(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(lambertW0_C(x));
    return __result;
END_RCPP
}
// lambertWm1_C
NumericVector lambertWm1_C(NumericVector x);
RcppExport SEXP lamW_lambertWm1_C(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(lambertWm1_C(x));
    return __result;
END_RCPP
}
