# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lambertW0_C <- function(x) {
    .Call('lamW_lambertW0_C', PACKAGE = 'lamW', x)
}

lambertWm1_C <- function(x) {
    .Call('lamW_lambertWm1_C', PACKAGE = 'lamW', x)
}

